# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
- name: deployment_name
  type: string
- name: deployment_file
  type: string
- name: enable_monitoring
  type: string
  default: 'false'

steps:
  - task: AzureCLI@2
    displayName: Create deployment
    continueOnError: true
    inputs: 
      azureSubscription: $(ado_service_connection_rg) #needs to have access at the RG level 
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        # Check if the virtual environment exists, create if it doesn't
        if [ ! -d ~/myagent/$(virtual_environment) ]; then
          echo "Creating virtual environment $(virtual_environment)"
          python3 -m venv ~/myagent/$(virtual_environment)
        else
          echo "Virtual environment $(virtual_environment) already exists"
        fi

        # Activate the virtual environment
        echo "Activating $(virtual_environment) virtual environment"
        source ~/myagent/$(virtual_environment)/bin/activate

        set -o xtrace
        az ml $(endpoint_type)-deployment create --name ${{ parameters.deployment_name }} --endpoint $(endpoint_name) \
          -f ${{ parameters.deployment_file }}

    env:
      PYTHONPATH: ~/myagent/$(virtual_environment)/lib/python3.12/site-packages:$(PYTHONPATH)