# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. Test 1

name: stage-model-testing

variables:
  - template: ../infrastructure/env-variables/config-infra-stage.yml
  - name: version
    value: ado-aml-cli-v2-templates
  - name: modelname
    value: automl

trigger: none

pool:
  name: Default

stages:
  - stage: EvaluateModelInStage
    displayName: Evaluate Model in Stage Environment
    jobs:
      - job: EvaluateModel
        timeoutInMinutes: 60
        steps:
          - template: ../ado-aml-cli-v2-templates/install-az-cli.yml
          - template: ../ado-aml-cli-v2-templates/install-aml-cli.yml
          - template: ../ado-aml-cli-v2-templates/connect-to-workspace.yml
          - template: ../ado-aml-cli-v2-templates/register-environment.yml
            parameters:
              environment_name: $(ds_environment)-env
              environment_file: $(Build.SourcesDirectory)/amlws-assets/environment/$(ds_environment)-env.yml
          - template: ../ado-aml-cli-v2-templates/create-compute.yml
            parameters:
              cluster_name: cpu-cluster
              size: Standard_DS3_v2
              min_instances: 0
              max_instances: 4
              cluster_tier: low_priority
          - template: ../ado-aml-cli-v2-templates/register-data.yml
            parameters:
              data_type: uri_file
              data_name: data
              data_file: $(ds_data)
          - template: ../ado-aml-cli-v2-templates/run-pipeline.yml
            parameters:
              pipeline_file: $(pipeline_file)
              experiment_name: stage_$(Build.Repository.Name)_evaluate_$(Build.SourceBranchName)
              display_name: stage_$(Build.Repository.Name)_run_$(Build.BuildID)
              enable_monitoring: $(enable_monitoring)
              modelname: ${{ variables.modelname }}
