# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: online-endpoint

variables:
  - template: ../infrastructure/env-variables/config-infra-stage.yml
  - name: endpoint_name
    value: $(Build.Repository.Name)-online-$(environment)-$(Build.BuildID)
  - name: deployment_name
    value: $(Build.Repository.Name)-online-$(environment)-$(Build.BuildID)-dp
  - name: endpoint_type
    value: online

trigger: none

pool:
  name: Default

stages:
  - stage: CreateOnlineEndpoint
    displayName: Create/Update Online Endpoint
    jobs:
      - job: DeployOnlineEndpoint
        steps:
          - template: ../aml-cli-v2/install-az-cli.yml
          - template: ../aml-cli-v2/install-aml-cli.yml
          - template: ../aml-cli-v2/connect-to-workspace.yml
          - template: ../aml-cli-v2/create-endpoint.yml
            parameters:
              endpoint_file: $(Build.SourcesDirectory)/mlops-pipelines/deploy/online/online-endpoint.yml
          - template: ../aml-cli-v2/create-deployment.yml
            parameters:
              deployment_name: $(Build.Repository.Name)-online-dp
              deployment_file: $(Build.SourcesDirectory)/mlops-pipelines/deploy/online/online-deployment.yml
          - template: ../aml-cli-v2/allocate-traffic.yml
            parameters:
              traffic_allocation: $(Build.Repository.Name)-online-dp=100
          - template: ../aml-cli-v2/test-deployment.yml
            parameters:
              deployment_name: $(Build.Repository.Name)-online-dp
              sample_request: $(Build.SourcesDirectory)/data-science/data/request.json
              request_type: json
