steps:
  - task: AzureCLI@2
    displayName: Register Azure ML environment 
    inputs: 
      azureSubscription: $(ado_service_connection_rg)
      scriptType: bash
      workingDirectory: $(System.DefaultWorkingDirectory)
      scriptLocation: inlineScript
      inlineScript: |
        set -e # fail on error

        # Check if the virtual environment exists, create if it doesn't
        if [ ! -d ~/myagent/$(virtual_environment) ]; then
          echo "Creating virtual environment $(virtual_environment)"
          python3 -m venv ~/myagent/$(virtual_environment)
        else
          echo "Virtual environment $(virtual_environment) already exists"
        fi

        # Activate the virtual environment
        echo "Activating $(virtual_environment) virtual environment"
        source ~/myagent/$(virtual_environment)/bin/activate

        az ml environment create --name ${{ parameters.environment_name }} --file ${{ parameters.environment_file }}

    env:
      PYTHONPATH: ~/myagent/$(virtual_environment)/lib/python3.12/site-packages:$(PYTHONPATH)